FROM amazonlinux:2023

RUN dnf install -y \
    docker \
    git \
    which \
    python3.13-pip

ARG USER_GID=100
ARG USER_UID=1000
ARG USER_NAME=ec2-user
ARG DOCKER_GID=1001
RUN grep $USER_GID /etc/group || groupadd -g $USER_GID $USER_NAME
RUN grep $DOCKER_GID /etc/group || groupadd -g $DOCKER_GID docker_group
RUN useradd -m --no-log-init -g $USER_GID -u $USER_UID $USER_NAME && usermod -aG $DOCKER_GID $USER_NAME

USER $USER_NAME:$USER_GID
RUN python3.13 -m venv $HOME/python-venv
ENV PATH=/home/$USER_NAME/python-venv/bin:$PATH
ENV VIRTUAL_ENV=/home/$USER_NAME/python-venv
RUN pip install --upgrade pip pyyaml requests jinja2
