FROM amazonlinux:2023

RUN dnf install -y \
    docker \
    git \
    which \
    python3.11-pip \
    python3-virtualenv

ARG USER_GID=100
ARG USER_UID=1000
ARG USER_NAME=ec2-user
ARG DOCKER_GID=1001
RUN grep $USER_GID /etc/group || groupadd -g $USER_GID $USER_NAME
RUN grep $DOCKER_GID /etc/group || groupadd -g $DOCKER_GID docker_group
RUN useradd -m --no-log-init -g $USER_GID -u $USER_UID $USER_NAME && usermod -aG $DOCKER_GID $USER_NAME

USER $USER_NAME:$USER_GID
RUN virtualenv -p python3.11 /home/$USER_NAME/.local/python-env
ENV PATH=/home/$USER_NAME/.local/python-env/bin:$PATH
ENV VIRTUAL_ENV=/home/$USER_NAME/.local/python-env
RUN pip3 install --upgrade pip pyyaml requests
