FROM public.ecr.aws/ubuntu/ubuntu:resolute

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    build-essential \
    python3-dev \
    python3-pip \
    python3-venv \
    libgl1 \
    libglib2.0-0 \
    tzdata

RUN python3 -m venv /python-venv
ENV PATH=/python-venv/bin:$PATH
ENV VIRTUAL_ENV=/python-venv
RUN pip install --upgrade pip
