FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-dev \
    python3-pip \
    python3-venv \
    libgl1 \
    libglib2.0-0 \
    tzdata

RUN /bin/bash -c "python3 -m venv /python-venv && source /python-venv/bin/activate && pip install --upgrade pip"
ENV PATH=/python-venv/bin:$PATH
ENV VIRTUAL_ENV=/python-venv
