FROM amazonlinux:2023

RUN dnf install -y \
        "@Development tools" \
        python3-devel \
        python3-pip \
        libgomp \
        mesa-libGL

RUN /bin/bash -c "python3 -m venv /python-venv && source /python-venv/bin/activate && pip install --upgrade pip"
ENV PATH=/python-venv/bin:$PATH
ENV VIRTUAL_ENV=/python-venv
